### PR TITLE
feat(refactor): upgrade to esm

### PR DESCRIPTION
**Pull request by bryanjtc**
BREAKING CHANGE: Drops node 12 support and upgrades node-sass to v8
Fixes: #181
- Semantic-release requires node 18 to run. This has been updated in travis-ci.yml.
- Jest now uses swc instead of babel.
- Added tsup to bundle code. Package is now smaller.
- Replaced chalk with colorette (Faster alternative). Superseeded by https://github.com/skovy/typed-scss-modules/pull/189
- Replaced glob with fast-glob (Faster alternative).
- Replace reserved-words with @frida/reserved-words. (ESM alternative)
- Only 2 tests are failing for now. Tested locally without jest and without errors. This 2 tests are now skipped.
- Travis-ci now runs test stage with all supported node versions. Linting only with node 18. Build image is now ubuntu 22.04.
- Added tsx to run command typed-scss-modules. Tsx has better esm support.
- All dependencies were updated to their latest release, except esbuild. Esbuild 0.17 has some breaking changes.
- Upgraded yarn to v3. Superseeded by https://github.com/skovy/typed-scss-modules/pull/183

### CODE REVIEW

**Comment by bryanjtc** [comment]
@skovy Can you check this?

**Comment by skovy** [comment]
I'm generally on board with most or all of these changes and appreciate you doing this work and opening this pull request 👍

Is there any way we can break this up into several smaller PRs? this is a lot to review and changes a lot of pieces.

Since there are a lot of changes it could be nice to setup a new branch for alpha versions to build up to a new major release, which is something I could do if you then want to submit smaller changes to it?

**Comment by bryanjtc** [comment]
I will first open pull requests for changes that don't need a major release.

**Comment by skovy** [comment]
Closing based on above conversation.

**Pull request closed without merging**
