### PR TITLE
Fixed keyframes generation by using css-tree package for parsing

### PR DESCRIPTION
**Pull request by kostaskriaridis**
### Fixed keyframes generation
1. Removed `css-modules-loader-core` package;
2. Added `css-tree` package for parsing css — high performant one;
3. Updated tests for keyframes generation check.

[Issue link](https://github.com/skovy/typed-scss-modules/issues/190)

### CODE REVIEW

**Comment by skovy** [comment]
Conceptually this makes sense to me and looks good. Since this is core functionality we need to run tests. I recently converted to using GitHub actions and it's not running correctly. I tried updating the config here, could you try opening a new PR or maybe force pushing to this branch again? https://github.com/skovy/typed-scss-modules/pull/193

**Comment by skovy** [comment]
It's working now! I had to approve. (wasn't an option before so thanks for merging!)

**Comment by skovy** [comment]
The `yarn.lock` diff is very large, is this all related to this package? It could also explain the failing build since it was passing on the master branch

**Comment by kostaskriaridis** [comment]
Good question, I have this version:
```
yarn -v
1.22.19
```

Seems like there is a version mismatch or something

**Comment by skovy** [comment]
I'm open to merging this, but haven't had time to debug the workflow and why it's failing.

**Comment by skovy** [comment]
See the attached issue for @keyframes (intended behavior).

I would also like to avoid re-implementing the CSS Modules spec which I believe this approach would require and instead use a package that is designed for CSS Modules. I think `postcss-modules` is that package.

**Pull request closed without merging**
