### PR TITLE
Add snake case class name transformer

### PR DESCRIPTION
**Pull request by JohnGurin**

### CODE REVIEW

**Comment by skovy** [comment]
@JohnGurin if you fix the failing build I can look at getting this merged.

**Comment by JohnGurin** [comment]
Outsmarted myself and forgot to push `yarn.lock` last time.
Btw, `node-sass` is far beyond v4.12, had to switch to Node 12 to make gyp build succeed on `yarn install`

**Review by skovy — APPROVED** [review]

**Comment by skovy** [comment]
4.12 is the last version that supported node 12, but that and shortly node 14 are/will both be end of life - https://nodejs.org/en/about/releases. we could bump this to the last version that supports node 14 but since it's a peer dependency it should work with any version you have installed matching or greater so I don't see any urgency in bumping that peer dependency since it's controlled by the consumer.

**Pull request merged**
