### PR TITLE
chore: upgrade node-sass, change css-modules-loader-core

### PR DESCRIPTION
**Pull request by bryanjtc**
The repository for `css-modules-loader-core` hasn't been updated in years, and it has vulnerabilities.
I found a replacement that is a fork from `css-modules-loader-core` and has been rewrited in typescript.
When I ran yarn install I had trouble with node-sass, so I updated it. You can undo that change.

### CODE REVIEW

**Comment by skovy** [comment]
hey, thanks for the contribution!

it doesn't look like there is much usage of this package (based on npm downloads / GitHub activity). therefore, I don't think I'm comfortable adding this package as a dependency. if the current package has vulnerabilities that's not good, but do you know what they are? it's possible it depends on packages that would have a vulnerability in the browser but wouldn't be a true threat running in a script locally. not saying that's the case here, but we should confirm the vulnerability is a true threat to users of this package before we swap to a random fork (which could pose a bigger threat)

as for `node-sass`, I think upgrading the version seems reasonable but since this package still supports v4 I think it's probably best we continue using the lowest common denominator (lowest supported version) for development to ensure it's still supported by the package

**Comment by skovy** [comment]
hey, thanks for the contribution!

it doesn't look like there is much usage of this package (based on npm downloads / GitHub activity). therefore, I don't think I'm comfortable adding this package as a dependency. if the current package has vulnerabilities that's not good, but do you know what they are? it's possible it depends on packages that would have a vulnerability in the browser but wouldn't be a true threat running in a script locally. not saying that's the case here, but we should confirm the vulnerability is a true threat to users of this package before we swap to a random fork (which could pose a bigger threat)

as for `node-sass`, I think upgrading the version seems reasonable but since this package still supports v4 I think it's probably best we continue using the lowest common denominator (lowest supported version) for development to ensure it's still supported by the package

**Comment by sfreedgood** [comment]
@skovy Context Regarding [node-sass](https://github.com/sass/node-sass/releases)
`node-sass ^7.0.0` supports Node 12, 14, 16, 17
`node-sass ^6.0.0` supports Node 12, 14, 15, 16
`node-sass ^5.0.0` supports Node 10, 12, 14, 15 and introduces new node-gyp version that supports building with Python 3
`node-sass ^4.14.0` supports Node 0.10, 0.12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14
`node-sass ^4.12.0` (current) supports Node 0.10, 0.12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

FWIW `node-ass@6.0.0` introduces support for Node v16, which is the minimum version supported by `ARM` (and by extension any Apple machines containing M1 chips).

**Comment by sfreedgood** [comment]
For anyone having issues with the `node-sass` version in their peer-dependencies, the solution I ended up using was: 
`npm v8` supports [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), which you can add to your `package.json`:
```json
"overrides": {
	"typed-scss-modules": {
		"node-sass": "7.0.1"
	}
}
```
cc @bryanjtc if it helps

**Pull request closed without merging**
