### PR TITLE
feat(node-sass): support 8.x as a peer dependency

### PR DESCRIPTION
**Pull request by glinford**
Update package.json to support node-sass 8.x as peer dependency

### CODE REVIEW

**Comment by skovy** [comment]
this solution looks great to me!

it looks like the tests didn't run, are you on the latest `master` branch commit? that should contain the workflow that should run here. your commit message will also need to follow commit conventions to allow merging, which should be checked via git hook locally and tests. something like `feat(node-sass): support 8.x as a peer depedency` as a commit message should also cause this to be released as a minor version.

**Comment by glinford** [comment]
I'm pretty sure I'm on master yes since I've used the github function to that change directly.
I'll amend the commit message and update, thanks

**Comment by glinford** [comment]
Commit message updated and verified I'm on latest master (I am)

**Comment by glinford** [comment]
@skovy is anything I can do ? I doesn't seems the workflow is running.

**Comment by skovy** [comment]
I don't understand why the tests aren't running on this branch, but this _shouldn't_ affect tests in any way and they should run on the main branch.

**Pull request merged**
